name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  # a workflow consists of a number of jobs. In this case, there is just one job, that is given the name 'build'.
  build:  # name of the job
    runs-on: ubuntu-latest

    steps:
    # A job consists of a series of steps. Each step is a small operation or action that does its part of the whole.
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/beermapping:latest